package dev.kyvora.api.auditlog.entity;

public enum AuditEventType {

	SERVER_CREATED,
	SERVER_UPDATED,
	SERVER_DELETED,
	SERVER_MARKED_ONLINE_BY_AGENT,
	SERVER_MARKED_OFFLINE_BY_AGENT,
	AGENT_CONFIGURED,
	AGENT_PULL_SUCCEEDED,
	AGENT_PULL_FAILED,
	AGENT_MARKED_ONLINE,
	AGENT_MARKED_OFFLINE,
	AGENT_DECOMMISSIONED,
	USER_LOGIN_SUCCEEDED,
	USER_LOGIN_FAILED,
	USER_LOGIN_BLOCKED_DISABLED,
	USER_CREATED,
	USER_UPDATED,
	USER_DISABLED,
	USER_ENABLED,
	USER_PASSWORD_RESET,
	USER_PASSWORD_CHANGED,
	USER_LOGOUT,
	TOKEN_REFRESHED,
	SETTINGS_UPDATED
}
