package dev.kyvora.api.auditlog.entity;

public enum AuditEventType {

	SERVER_CREATED,
	SERVER_UPDATED,
	SERVER_DELETED,
	AGENT_REGISTERED,
	AGENT_HEARTBEAT_RECEIVED,
	AGENT_MARKED_OFFLINE,
	USER_LOGIN_SUCCEEDED,
	USER_LOGIN_FAILED,
	USER_LOGOUT,
	TOKEN_REFRESHED
}
