package dev.kyvora.api.auditlog.entity;

public enum AuditEventType {

	SERVER_CREATED,
	SERVER_UPDATED,
	SERVER_DELETED,
	SERVER_MARKED_ONLINE_BY_AGENT,
	SERVER_MARKED_OFFLINE_BY_AGENT,
	AGENT_REGISTERED,
	AGENT_ENROLLED,
	AGENT_CONNECTED,
	AGENT_HEARTBEAT_RECEIVED,
	AGENT_MARKED_ONLINE,
	AGENT_MARKED_OFFLINE,
	AGENT_TOKEN_ROTATED,
	AGENT_ENROLLMENT_CANCELED,
	USER_LOGIN_SUCCEEDED,
	USER_LOGIN_FAILED,
	USER_LOGOUT,
	TOKEN_REFRESHED
}
