spring:
  application:
    name: kyvora-api

  profiles:
    default: local

  datasource:
    url: ${KYVORA_DATASOURCE_URL:jdbc:postgresql://ictnikhadlk01:5432/kyvora}
    username: ${KYVORA_DATASOURCE_USERNAME:kyvora}
    password: ${KYVORA_DATASOURCE_PASSWORD:kyvora}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: ${KYVORA_API_PORT:8080}

logging:
  level:
    root: ${KYVORA_LOG_LEVEL_ROOT:INFO}
    dev.kyvora.api: ${KYVORA_LOG_LEVEL_APP:INFO}
    org.springframework.security: ${KYVORA_LOG_LEVEL_SECURITY:WARN}
    org.hibernate.SQL: ${KYVORA_LOG_LEVEL_SQL:WARN}
  file:
    name: ${KYVORA_LOG_FILE:logs/kyvora-api.log}
  logback:
    rollingpolicy:
      max-file-size: ${KYVORA_LOG_MAX_FILE_SIZE:10MB}
      max-history: ${KYVORA_LOG_MAX_HISTORY:14}
      total-size-cap: ${KYVORA_LOG_TOTAL_SIZE_CAP:256MB}
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info

kyvora:
  jwt:
    secret: ${KYVORA_JWT_SECRET:dev-only-change-me-dev-only-change-me}
    access-token-ttl-seconds: ${KYVORA_JWT_ACCESS_TOKEN_TTL_SECONDS:900}
    refresh-token-ttl-seconds: ${KYVORA_REFRESH_TOKEN_TTL_SECONDS:2592000}
