spring:
  datasource:
    url: ${KYVORA_DATASOURCE_URL}
    username: ${KYVORA_DATASOURCE_USERNAME}
    password: ${KYVORA_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: ${KYVORA_LOG_LEVEL_ROOT:INFO}
    dev.kyvora.api: ${KYVORA_LOG_LEVEL_APP:INFO}
    org.springframework.security: ${KYVORA_LOG_LEVEL_SECURITY:WARN}
    org.hibernate.SQL: ${KYVORA_LOG_LEVEL_SQL:WARN}
  file:
    name: ${KYVORA_LOG_FILE:/var/log/kyvora/kyvora-api.log}

kyvora:
  jwt:
    secret: ${KYVORA_JWT_SECRET}
