spring:
  application:
    name: kyvora-api

  security:
    user:
      name: ${KYVORA_SECURITY_USERNAME:user}
      password: ${KYVORA_SECURITY_PASSWORD:dev-password}

  datasource:
    url: jdbc:postgresql://ictnikhadlk01:5432/kyvora
    username: kyvora
    password: kyvora

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
