package dev.kyvora.api.agent.event;

public enum AgentEventType {

	AGENT_REGISTERED,
	AGENT_ENROLLED,
	AGENT_CONNECTED,
	AGENT_HEARTBEAT_RECEIVED,
	AGENT_MARKED_ONLINE,
	AGENT_MARKED_OFFLINE,
	AGENT_TOKEN_ROTATED,
	AGENT_ENROLLMENT_CANCELED
}
